baseURL: "https://llapis.vercel.app/"
languageCode: "en-us"
title: "🙋‍♂️ Hi, I'm Nhật Anh"
theme: hugopro5

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  # main:
    # - identifier: blog
    #   name: Blogs
    #   title: Blogs Post
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Hi, I'm Nhật Anh"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/llapis.jpg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    #brandLogo: "/llapis.jpg" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Mai Dang Nhat Anh" # Brand name for the brand | default is the title variable
    disableSearch: True
    #searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: True
      disableProjects: False
      disableAchievements: True
      disableContact: False

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Nhat Anh."
    subtitle: "The harder you work, the luckier you get"
    content: "A dedicated Data Engineer. I focus on designing and optimizing data pipelines to ensure seamless data flow and efficient processing."
    image: /images/anhport.jpeg
    #/images/hero.svg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/pdf/CV_DE_Mai_Dang_Nhat_Anh.pdf"
      download: false
      newPage: false

    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/mdnanh
        # - icon: fab fa-x-twitter
        #   url: https://example.com
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/llapis.jpg"
    content: |-
      I’m an enthusiastic and motivated data engineer at the start of my career, eager to apply my academic knowledge and hands-on learning in the field. I’m excited about the opportunity to contribute to meaningful projects, collaborate with talented teams, and continue to grow as a data professional

      Looking ahead, my long-term goal is to become a specialist in data engineering, designing and implementing efficient data systems, while contributing to the organization's success and continuing my professional growth within the company.
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "Python"
        - "Apache Spark"
        - "SQL"
        - "Kafka"
        - "MongoDB"
        - "Apache Superset"
        - "ETL, ELT"
        - "Docker"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "AI Engineer Intern"
        company: "Bitdance Technologies and Entertainment Company"
        date: " Oct 2023 – Jan 2024"
        # featuredLink:
        #   enable: true
        #   name: "View the project"
        #   url: "https://example.com"
        content: "At Bitdance Technologies, I applied large language models (LLMs) to innovate in content analysis and music creation, exploring their technical and creative potential. I developed retrieval-based question-answering systems as part of Retrieval-Augmented Generation (RAG) pipelines, leveraging advanced sentence embedding techniques. Additionally, I contributed to optimizing and evaluating embedding models, improving the accuracy and efficiency of retrieval systems, and gaining valuable insights into the intersection of AI and the creative industries."

      - job: "Data Science Intern"
        company: "Stech Technology Joint Stock Company"
        date: "May 2023 – Aug 2023"
        # featuredLink:
        #   enable: true
        #   url: "https://example.com"
        # info:
        #   enable: true
        #   content: I worked as a software developer for more than one year in Amazon.
        content: "At Stech Technology, I gathered and prepared labeled datasets by crawling product review data from e-commerce platforms, laying the foundation for model training and evaluation. I researched and developed sentiment classification models and aspect-based sentiment analysis to uncover key factors driving customer evaluations. This internship honed my skills in natural language processing (NLP), self-learning, research methodologies, and presenting technical findings effectively."

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      # - title: "Master of Business Administration"
      #   school:
      #     name: "University of California, Berkeley"
      #     url: "https://example.org"
      #   date: "2013 - 2015"
      #   GPA: "3.8 out of 5.0"
      #   content: |-
      #     Extracurricular Activities
      #       - Lorem ipsum dolor sit amet consectetur adipisicing elit.
      #       - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Data Science"
        school:
          name: "International University - VNU HCMC"
          url: "https://hcmiu.edu.vn/"
        date: "Class of 2019"
        # GPA: "3.9 out of 5.0"
        content: |-
          Coursework:
          - Data Analysis, Fundamentals of Big Data Technology, Data Science and Data Visualization, Principles
          of Database Management, Algorithms & Data Structures,v.v
        # featuredLink:
        #   enable: true
        #   name: "My academic record"
        #   url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    title: "Projects"
    items:
      - title: Streaming E-Commerce Data Engineering
        content: A streaming data processing project, building a real-time pipeline for an e-commerce platform. The project focuses on collecting, processing, and visualizing customer and transaction data.
        url: /projects/streamingrealtime
        image: /images/projects/streaming/streamingecom.png
        featured:
          name: Read more
          link: /projects/streamingrealtime
        badges:
          - Apache Spark
          - Apache Druid
          - Apache Kafka
          - MiniO
        links:
          - icon: fab fa-github
            url: https://github.com/mdnanh/StreamingEcommerceDE
      - title: Customer Analysis BigData
        content: A customer analysis project leveraging big data tools to analyze and derive insights from large customer datasets. The project focuses on identifying trends, behaviors, and patterns to support data-driven business decisions.
        url: /projects/customerbd
        image: /images/projects/customer/CA.png
        featured:
          name: Read more
          link: /projects/customerbd
        badges:
          - "Apache Spark"
          - "MySQL"
          - "ETL,ELT"
        links:
          - icon: fab fa-github
            url: https://github.com/mdnanh/CustomerAnalysisBigData
      - title: CDCAnalysisRecruitment
        content: A project focused on analyzing customer data using change data capture (CDC) techniques. It enables efficient and real-time synchronization of customer data for recruitment processes, ensuring up-to-date insights.
        url: /projects/CDCRecruit
        image: /images/projects/CDCRecruit/recruitCDC.png
        featured:
          name: Read more
          link: /projects/cdcrecruit
        badges:
          - "Apache Spark"
          - "MySQL"
          - "ETL,ELT"
          - "Cassandra"
          - "Apache Kafka"
        links:
          - icon: fab fa-github
            url: https://github.com/mdnanh/CDCAnalysisRecruitment
    #   - title: Hugo Profile V2
    #     content: A clean and simple Hugo template for personal portfolio and blog.
    #     image: /images/projects/profile2.jpg
    #     featured:
    #       name: Demo V2
    #       link: https://hugo-profile-2.netlify.app
    #     badges:
    #       - "Hugo"
    #       - "Bootstrap"
    #       - "Javascript"
    #     links:
    #       - icon: fab fa-github
    #         url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    title: "Contact"
    content: "Feel free to reach out if you have any questions!"

    phone: "+84 97 153 8165"
    email: "mdna.tl2112@gmail.com"
    address: "Ho Chi Minh city, Vietnam"

  footer:
    # recentPosts:
    #   path: "blogs"
    #   count: 3
    #   title: Recent Posts
    #   enable: true
    #   disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/mdnanh
      facebook: https://www.facebook.com/nnhatanh/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
